version = 1

[[annotations]]
path = ["examples/create_env"]
precedence = "aggregate"
SPDX-FileCopyrightText = ["RTE (https://www.rte-france.com)"]
SPDX-License-Identifier = "MPL-2.0"

[[annotations]]
path = ["test/functional_test/cable_catalog.csv"]
precedence = "aggregate"
SPDX-FileCopyrightText = ["RTE (https://www.rte-france.com)"]
SPDX-License-Identifier = "MPL-2.0"

[[annotations]]
path = ["thermohl-docs/docs/assets/images/logos/*.ico", "thermohl-docs/docs/assets/images/logos/*.png", "thermohl-docs/docs/assets/images/*.png"]
precedence = "aggregate"
SPDX-FileCopyrightText = ["RTE (https://www.rte-france.com)"]
SPDX-License-Identifier = "MPL-2.0"

[[annotations]]
path = ["thermohl-docs/docs/examples/*.ipynb"]
precedence = "aggregate"
SPDX-FileCopyrightText = ["RTE (https://www.rte-france.com)"]
SPDX-License-Identifier = "MPL-2.0"
